"""Add details column to User model

Revision ID: 660a2b1c2633
Revises: 169416034b0e
Create Date: 2024-01-31 08:56:43.229832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660a2b1c2633'
down_revision = '169416034b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_details'), ['details'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_details'))
        batch_op.drop_column('details')

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
